### ISSUE TITLE
Create a production-ready adapter interface for the Kinesis client

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/shunting-yard#11]
_As a Shunting Yard developer_
_I'd like to write a Kinesis adapter_
_So I can safely use KCL as the event receiver_

## Overview
Shunting Yard uses polling to read messages from the topic, transform them and invoke [Circus Train](https://github.com/HotelsDotCom/circus-train).
KCL provides an out-of-the-box push client which includes features like rebalancing, load balancing, etc. Writing a poll client with all this features is not easy and it will take time to code, test it and make sure it works as expected.
We would like to reuse this KCL client in CT Event Based so we must write a robust adapter interface to adapt the KCL push protocol to the CT polling mechanism. At the moment this has been done with a `BlockingQueue`.

**Comment by massdosage** [comment]
Decided we're not going to use Kinesis for now so closing.
