### ISSUE TITLE
Run as a "fully executable application for Unix systems"

### ISSUE THREAD

**Issue by massdosage** [HotelsDotCom/shunting-yard#25]
As a user of Shunting Yard
I want to be able to deploy it as a Unix service
So that I can start it, stop it and query its status like I would any other Unix service
and so that it shuts down gracefully without dropping any in-progress replications.

h2. Acceptance Criteria
* Shunting yard deployable as a Unix service (see https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html) [TODO: figure out whether init.d or systemd are recommended by AWS and use those as the default run environment will be on EMR].
* On start the service goes into the loop where it tries to read messages forver.
* On stop the service
** Stops reading any new messages
** Runs any replications that are currently queued up in any of the receivers (e.g. aggregated)
** Waits for all in-progress replications to complete
** Only then does it shutdown and the service exits

**Comment by abhimanyugupta07** [comment]
Shunting Yard is now running inside a Docker container and managed by Amazon ECS. Thats why its better for it to be running using a shell script to leverage the auto-restart, monitoring and cloudwatch logging features provided by ECS. So, this is not necessary. It will be revisited once we have an actual use case.
