### ISSUE TITLE
Create an OffsetCommitter abstraction for the event receiver

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/shunting-yard#3]
_As a Shunting Yard developer_
_I'd like to have control the offset commits_
_So I can make sure that only successfully processed messages are committed and failures can be reprocessed_

## Overview

Both Kinesis and Kafka receivers commit the offset as soon as the messages are read. This may be a issue if the application fails to process any of the read events.

**Comment by massdosage** [comment]
Decided we're not supporting Kafka or Kinesis for now so closing.
