### ISSUE TITLE
Allow users to select the tables to be replicated

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/shunting-yard#6]
_As a Shunting Yard user_
_I'd like to be able to select the tables to be replicated from a source metastore_
_So I can only replicate those that are of interest for the analysts/applications_

## Acceptance criteria
User must be able to select tables from on of the pre-configured source metastores and select the target metastores where the table must be replicated.

**Comment by ddcprg** [comment]
Note description mentions that there might be more than one source and more than one replica so this issue depends on another which I'll be creating shortly

**Comment by massdosage** [comment]
We should try allow Regular Expressions for choosing the tables (https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html) in a similar fashion to what we do in the Waggle Dance whitelisting.
